version: 2
updates:
  - package-ecosystem: cargo
    directory: /agent
    schedule:
      interval: weekly
    labels:
      - dependencies
  - package-ecosystem: cargo
    directory: /host
    schedule:
      interval: weekly
    labels:
      - dependencies
