// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod agora {
        pub mod agent {
            /// The agora coordination protocol — the WIT contract every agent shares.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod protocol {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// FIPA-style speech acts: the structural intent layer (typed performatives
                /// standardize communicative intent independent of payload).
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Act {
                    Inform,
                    Request,
                    Propose,
                    Agree,
                    Refuse,
                }
                impl ::core::fmt::Debug for Act {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Act::Inform => f.debug_tuple("Act::Inform").finish(),
                            Act::Request => f.debug_tuple("Act::Request").finish(),
                            Act::Propose => f.debug_tuple("Act::Propose").finish(),
                            Act::Agree => f.debug_tuple("Act::Agree").finish(),
                            Act::Refuse => f.debug_tuple("Act::Refuse").finish(),
                        }
                    }
                }
                impl Act {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Act {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Act::Inform,
                            1 => Act::Request,
                            2 => Act::Propose,
                            3 => Act::Agree,
                            4 => Act::Refuse,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// A coordination message envelope.
                /// - `from` is the signed persona identity (self/peer distinguishability).
                /// - `sig` is the sigil signature (STUBBED in this spike — real wsc swaps in).
                /// - `hops` is the TTL that structurally bounds reaction cascades.
                #[derive(Clone)]
                pub struct Message {
                    pub id: u64,
                    pub sender: _rt::String,
                    pub channel: _rt::String,
                    pub act: Act,
                    pub payload: _rt::String,
                    pub sig: _rt::String,
                    pub hops: u32,
                }
                impl ::core::fmt::Debug for Message {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Message")
                            .field("id", &self.id)
                            .field("sender", &self.sender)
                            .field("channel", &self.channel)
                            .field("act", &self.act)
                            .field("payload", &self.payload)
                            .field("sig", &self.sig)
                            .field("hops", &self.hops)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_coordinate_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let base16 = arg2;
                    let len16 = arg3;
                    let mut result16 = _rt::Vec::with_capacity(len16);
                    for i in 0..len16 {
                        let base = base16
                            .add(i * (8 + 10 * ::core::mem::size_of::<*const u8>()));
                        let e16 = {
                            let l1 = *base.add(0).cast::<i64>();
                            let l2 = *base.add(8).cast::<*mut u8>();
                            let l3 = *base
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len4 = l3;
                            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                            let l5 = *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *base
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len7 = l6;
                            let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                            let l8 = i32::from(
                                *base
                                    .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            let l9 = *base
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l10 = *base
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len11 = l10;
                            let bytes11 = _rt::Vec::from_raw_parts(
                                l9.cast(),
                                len11,
                                len11,
                            );
                            let l12 = *base
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l13 = *base
                                .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len14 = l13;
                            let bytes14 = _rt::Vec::from_raw_parts(
                                l12.cast(),
                                len14,
                                len14,
                            );
                            let l15 = *base
                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>();
                            Message {
                                id: l1 as u64,
                                sender: _rt::string_lift(bytes4),
                                channel: _rt::string_lift(bytes7),
                                act: Act::_lift(l8 as u8),
                                payload: _rt::string_lift(bytes11),
                                sig: _rt::string_lift(bytes14),
                                hops: l15 as u32,
                            }
                        };
                        result16.push(e16);
                    }
                    _rt::cabi_dealloc(
                        base16,
                        len16 * (8 + 10 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result17 = T::coordinate(_rt::string_lift(bytes0), result16);
                    let ptr18 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec24 = result17;
                    let len24 = vec24.len();
                    let layout24 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec24.len() * (8 + 10 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result24 = if layout24.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout24).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout24);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec24.into_iter().enumerate() {
                        let base = result24
                            .add(i * (8 + 10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let Message {
                                id: id19,
                                sender: sender19,
                                channel: channel19,
                                act: act19,
                                payload: payload19,
                                sig: sig19,
                                hops: hops19,
                            } = e;
                            *base.add(0).cast::<i64>() = _rt::as_i64(id19);
                            let vec20 = (sender19.into_bytes()).into_boxed_slice();
                            let ptr20 = vec20.as_ptr().cast::<u8>();
                            let len20 = vec20.len();
                            ::core::mem::forget(vec20);
                            *base
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len20;
                            *base.add(8).cast::<*mut u8>() = ptr20.cast_mut();
                            let vec21 = (channel19.into_bytes()).into_boxed_slice();
                            let ptr21 = vec21.as_ptr().cast::<u8>();
                            let len21 = vec21.len();
                            ::core::mem::forget(vec21);
                            *base
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len21;
                            *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr21.cast_mut();
                            *base
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (act19.clone() as i32) as u8;
                            let vec22 = (payload19.into_bytes()).into_boxed_slice();
                            let ptr22 = vec22.as_ptr().cast::<u8>();
                            let len22 = vec22.len();
                            ::core::mem::forget(vec22);
                            *base
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len22;
                            *base
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr22.cast_mut();
                            let vec23 = (sig19.into_bytes()).into_boxed_slice();
                            let ptr23 = vec23.as_ptr().cast::<u8>();
                            let len23 = vec23.len();
                            ::core::mem::forget(vec23);
                            *base
                                .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len23;
                            *base
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr23.cast_mut();
                            *base
                                .add(8 + 9 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(hops19);
                        }
                    }
                    *ptr18.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len24;
                    *ptr18.add(0).cast::<*mut u8>() = result24;
                    ptr18
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_coordinate<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base10 = l0;
                    let len10 = l1;
                    for i in 0..len10 {
                        let base = base10
                            .add(i * (8 + 10 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(8).cast::<*mut u8>();
                            let l3 = *base
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                            let l6 = *base
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                            let l8 = *base
                                .add(8 + 7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *base
                                .add(8 + 8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base10,
                        len10 * (8 + 10 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                }
                pub trait Guest {
                    /// Pure coordination logic. The host (the transport + capability layer, where
                    /// NATS/JetStream swaps in) hands the agent ONLY the messages it is allowed to
                    /// see — already capability-scoped to its granted channels and self-echo
                    /// filtered — and the component decides what to emit. The component holds no
                    /// ambient authority: it cannot reach a channel it was not handed.
                    fn coordinate(
                        me: _rt::String,
                        inbox: _rt::Vec<Message>,
                    ) -> _rt::Vec<Message>;
                }
                #[doc(hidden)]
                macro_rules! __export_agora_agent_protocol_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "agora:agent/protocol#coordinate")] unsafe extern "C" fn
                        export_coordinate(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_coordinate_cabi::<$ty > (arg0, arg1, arg2, arg3) } }
                        #[unsafe (export_name =
                        "cabi_post_agora:agent/protocol#coordinate")] unsafe extern "C"
                        fn _post_return_coordinate(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_coordinate::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_agora_agent_protocol_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_agent_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::agora::agent::protocol::__export_agora_agent_protocol_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::agora::agent::protocol);
    };
}
#[doc(inline)]
pub(crate) use __export_agent_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:agora:agent:agent:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 324] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc8\x01\x01A\x02\x01\
A\x02\x01B\x07\x01m\x05\x06inform\x07request\x07propose\x05agree\x06refuse\x04\0\
\x03act\x03\0\0\x01r\x07\x02idw\x06senders\x07channels\x03act\x01\x07payloads\x03\
sigs\x04hopsy\x04\0\x07message\x03\0\x02\x01p\x03\x01@\x02\x02mes\x05inbox\x04\0\
\x04\x04\0\x0acoordinate\x01\x05\x04\0\x14agora:agent/protocol\x05\0\x04\0\x11ag\
ora:agent/agent\x04\0\x0b\x0b\x01\0\x05agent\x03\0\0\0G\x09producers\x01\x0cproc\
essed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
